# .pre-commit-config.yaml

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # Use a versão mais recente
    hooks:
    -   id: detect-private-key
        name: Bloqueia a palavra 'print'
        # Adiciona o padrão 'print(' como uma regex para detecção
        # O argumento --regex permite que você defina o padrão de busca.
        args: ['--regex', 'print\s*\(']
        # Limita a verificação a arquivos Python (.py)
        files: \.py$
        # Exclui a verificação em um arquivo específico, se necessário
        # exclude: setup\.py
